### ISSUE TITLE
Profile TPC-DS queries

### ISSUE THREAD

**Issue by mweisgut** [hyrise-mp/hyrise#10]
Requires #12 

How long do those TPC-DS queries run that Hyrise can execute?
Check out these resources:
- [ ] Master thesis of @lanice 
- [ ] https://github.com/hyrise/hyrise/wiki/Profiling

Consider using these tools:
- [ ] intel VTune
- [ ] intel Memory Latency Checker
- [ ] Performance Counter Monitor (better than perf)
- [ ] Execute multi-threading (use script)

Questions:
- [ ] What are the most expensive operators?

**Comment by mweisgut** [comment]
#57

**Comment by mweisgut** [comment]
a1131032f

**Comment by mweisgut** [comment]
https://github.com/hyrise-mp/hyrise/blob/benchmark/doc/doc.md

**Comment by janetzki** [comment]
@julianmenzler This issue looks like what you have done over the past months. Would you consider it closed?

**Comment by julianmenzler** [comment]
Yes, I would! 👍
