### ISSUE TITLE
Optimize Query 31

### ISSUE THREAD

**Issue by janetzki** [hyrise-mp/hyrise#56]
- Do not execute the same Sub-LQP twice
- Hash LQPs, put them into an unordered map, look if they have already been computed, create a diamond structure
- Also useful for TPC-H 15

**Comment by mweisgut** [comment]
Creating hash values for  LQP subtrees is just the first step for the optimization. Hash values are ambiguous. If we found equal hash values, we have to check if the subtrees are actually equal.

**Comment by mweisgut** [comment]
https://github.com/hyrise/hyrise/pull/1795
