### ISSUE TITLE
Execution comparison with DuckDB

### ISSUE THREAD

**Issue by mweisgut** [hyrise-mp/hyrise#58]
Compare Hyrise's executions times and query plans with those of [DuckDB](https://www.duckdb.org/).

**Comment by jackvincenow** [comment]
Any initial insights into the diff between the two projects?

**Comment by mweisgut** [comment]
Yes, we have these [benchmark comparisons](https://docs.google.com/spreadsheets/d/1kLQsY0ZAqq0r6qVbFXgeff1p78nbXw1WMGq_k3KZBrY/edit#gid=1987090153).
