### ISSUE TITLE
Evaluate query differences between official templates and used queries

### ISSUE THREAD

**Issue by mweisgut** [hyrise-mp/hyrise#67]
At the beginning of the project, we did not use the query repository that we are currently using but used queries generated by the original tpc-ds toolkit. Using these toolkit generated queries, we evaluated which queries are supported by Hyrise. During the project we switched to the query repository that we are using now but did not evaluate the executability of the queries again.

Therefore, it might be the case that other queries currently classified as "not supported by Hyrise" differ from the officially provided query templates.

**Comment by janetzki** [comment]
I requested more clarification int https://github.com/cwida/tpcds-result-reproduction/issues/6.
